spring.datasource.url=${DB_URL:jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:aSZedROqOlKTLaBtKzFeJqgMPWysAaHs}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=${JWT_SECRET:qW8H7v+fVtP1e3R2iK9N6J8xYgR4lO2qE3vK7sL0hP5dF1gH2jK4mN8pR0sV6tX9qW8H7v+fVtP1e3R2iK9N6J8xYgR4lO2qE3vK7sL0hP5dF1gH2jK4mN8pR0sV6tX9}
jwt.expiration=100000000

server.port=${PORT:8080}
